// flow-typed signature: 6d9036973aa1c2c74b81ecb7d53e4aad
// flow-typed version: <<STUB>>/react-spin_v^0.6.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spin/karma.conf' {
  declare module.exports: any;
}

declare module 'react-spin/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spin/karma.conf.js' {
  declare module.exports: $Exports<'react-spin/karma.conf'>;
}
declare module 'react-spin/lib/main.js' {
  declare module.exports: $Exports<'react-spin/lib/main'>;
}
