// flow-typed signature: 2352f42dba4d1eb42da2e72b7e768ea9
// flow-typed version: <<STUB>>/react-mixins_v^0.1.6/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mixins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mixins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mixins/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mixins/dist/index.js' {
  declare module.exports: $Exports<'react-mixins/dist/index'>;
}
