// flow-typed signature: fdcb3b3dc3f012c44e33bb5d4c7840a6
// flow-typed version: <<STUB>>/s_v^0.1.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   's'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 's' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 's/s' {
  declare module.exports: any;
}

declare module 's/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 's/s.js' {
  declare module.exports: $Exports<'s/s'>;
}
declare module 's/test.js' {
  declare module.exports: $Exports<'s/test'>;
}
