// @flow

export const UPDATE_CONFIG ='UPDATE_CONFIG';

export const JUDGE_REQUEST = 'JUDGE_REQUEST';
export const SUBMISSION_PUBLISHED = 'SUBMISSION_PUBLISHED';

export const FETCH_PROBLEMS_REQUEST = 'FETCH_PROBLEMS_REQUEST';
export const FETCH_PROBLEMS_SUCCESS = 'FETCH_PROBLEMS_SUCCESS';

export const FETCH_SUBMISSIONS = 'FETCH_SUBMISSIONS';
export const FETCH_SUBMISSIONS_STATS = 'FETCH_SUBMISSIONS_STATS';

export const FETCH_PROBLEM_RANKING = 'FETCH_PROBLEM_RANKING';
export const FETCH_RANKING = 'FETCH_RANKING';
export const FETCH_PREVIOUS_RANKING = 'FETCH_PREVIOUS_RANKING';
export const FETCH_RANKING_START_DATE = 'FETCH_RANKING_START_DATE';

export const PROBLEM_REFRESH = 'PROBLEM_REFRESH';
export const SET_CURRENT_PROBLEM = 'SET_CURRENT_PROBLEM';
export const CHANGE_SOURCE_CODE = 'CHANGE_SOURCE_CODE';

export const HIDE_DONE_PROBLEMS = 'HIDE_DONE_PROBLEMS';
export const SET_PROBLEMS_DIFFICULTY_VISIBILITY_FILTER = 'SET_PROBLEMS_DIFFICULTY_VISIBILITY_FILTER';

export const SET_SUBMISSIONS_FILTER = 'SET_SUBMISSIONS_FILTER';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CHECKED_SESSION_STATUS = 'CHECKED_SESSION_STATUS';

export const FETCH_USERS = 'FETCH_USERS';

export const NAVIGATE_AWAY_FROM_AUTH_FORM = 'NAVIGATE_AWAY_FROM_AUTH_FORM';
export const CLOSE_WORK_IN_PROGRESS_WINDOW = 'CLOSE_WORK_IN_PROGRESS_WINDOW';

export const FETCH_PROBLEMS_SOLUTION_RATIO = 'FETCH_PROBLEMS_SOLUTION_RATIO';

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export const WEBSOCKET_CONNECTED = 'WEBSOCKET_CONNECTED';